//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEBIDA_BAR
    {
        public BEBIDA_BAR()
        {
            this.RECETA = new HashSet<RECETA>();
            this.ORDEN_BEBIDA = new HashSet<ORDEN_BEBIDA>();
        }
    
        public decimal ID_BEBIDA { get; set; }
        public string NOM_BEBIDA { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public byte[] IMAGEN { get; set; }
    
        public virtual ICollection<RECETA> RECETA { get; set; }
        public virtual ICollection<ORDEN_BEBIDA> ORDEN_BEBIDA { get; set; }
    }
}
