//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGA
    {
        public BODEGA()
        {
            this.RECETA = new HashSet<RECETA>();
        }
    
        public string NUM_BODEGA { get; set; }
        public string UBICACION { get; set; }
    
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
