//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJA_FACTURA
    {
        public decimal NUM_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        public string EMISOR { get; set; }
        public string DESCRIPCION { get; set; }
        public string FORMA_PAGO { get; set; }
        public string METODO_PAGO { get; set; }
        public Nullable<decimal> BASE { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public decimal ORDEN_NUM_ORDEN { get; set; }
    
        public virtual ORDEN ORDEN { get; set; }
    }
}
