//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BEBIDA_BAR> BEBIDA_BAR { get; set; }
        public DbSet<BODEGA> BODEGA { get; set; }
        public DbSet<CAJA_FACTURA> CAJA_FACTURA { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<ESTADO_ORDEN> ESTADO_ORDEN { get; set; }
        public DbSet<INGREDIENTES> INGREDIENTES { get; set; }
        public DbSet<LOCAL> LOCAL { get; set; }
        public DbSet<MESA> MESA { get; set; }
        public DbSet<ORDEN> ORDEN { get; set; }
        public DbSet<ORDEN_DETALLES> ORDEN_DETALLES { get; set; }
        public DbSet<PLATO_COCINA> PLATO_COCINA { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECETA> RECETA { get; set; }
        public DbSet<RECETA_INGREDIENTE> RECETA_INGREDIENTE { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<TIPO_EMPLEADO> TIPO_EMPLEADO { get; set; }
        public DbSet<ESTADO_CUENTA> ESTADO_CUENTA { get; set; }
    
        public virtual int CREATE_MESA(Nullable<decimal> nUMMESA, string eSTADMESA, Nullable<decimal> lOCALNUM)
        {
            var nUMMESAParameter = nUMMESA.HasValue ?
                new ObjectParameter("NUMMESA", nUMMESA) :
                new ObjectParameter("NUMMESA", typeof(decimal));
    
            var eSTADMESAParameter = eSTADMESA != null ?
                new ObjectParameter("ESTADMESA", eSTADMESA) :
                new ObjectParameter("ESTADMESA", typeof(string));
    
            var lOCALNUMParameter = lOCALNUM.HasValue ?
                new ObjectParameter("LOCALNUM", lOCALNUM) :
                new ObjectParameter("LOCALNUM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATE_MESA", nUMMESAParameter, eSTADMESAParameter, lOCALNUMParameter);
        }
    
        public virtual int DELETE_MESA(Nullable<decimal> nUMMESA)
        {
            var nUMMESAParameter = nUMMESA.HasValue ?
                new ObjectParameter("NUMMESA", nUMMESA) :
                new ObjectParameter("NUMMESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_MESA", nUMMESAParameter);
        }
    
        public virtual int LISTABEBIDAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTABEBIDAS");
        }
    
        public virtual int LISTAMESAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTAMESAS");
        }
    
        public virtual int LISTAPLATOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTAPLATOS");
        }
    
        public virtual int MODIFICAR_MESA(Nullable<decimal> nUMMESA, string eSTADMESA, Nullable<decimal> lOCALNUM)
        {
            var nUMMESAParameter = nUMMESA.HasValue ?
                new ObjectParameter("NUMMESA", nUMMESA) :
                new ObjectParameter("NUMMESA", typeof(decimal));
    
            var eSTADMESAParameter = eSTADMESA != null ?
                new ObjectParameter("ESTADMESA", eSTADMESA) :
                new ObjectParameter("ESTADMESA", typeof(string));
    
            var lOCALNUMParameter = lOCALNUM.HasValue ?
                new ObjectParameter("LOCALNUM", lOCALNUM) :
                new ObjectParameter("LOCALNUM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_MESA", nUMMESAParameter, eSTADMESAParameter, lOCALNUMParameter);
        }
    
        public virtual int CREATE_RESERVA(Nullable<decimal> nUMRESERVA, Nullable<System.DateTime> fECHA, string hORA, Nullable<decimal> cLIENTE_RUT, Nullable<decimal> cANTIDAD_PERSONAS)
        {
            var nUMRESERVAParameter = nUMRESERVA.HasValue ?
                new ObjectParameter("NUMRESERVA", nUMRESERVA) :
                new ObjectParameter("NUMRESERVA", typeof(decimal));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var hORAParameter = hORA != null ?
                new ObjectParameter("HORA", hORA) :
                new ObjectParameter("HORA", typeof(string));
    
            var cLIENTE_RUTParameter = cLIENTE_RUT.HasValue ?
                new ObjectParameter("CLIENTE_RUT", cLIENTE_RUT) :
                new ObjectParameter("CLIENTE_RUT", typeof(decimal));
    
            var cANTIDAD_PERSONASParameter = cANTIDAD_PERSONAS.HasValue ?
                new ObjectParameter("CANTIDAD_PERSONAS", cANTIDAD_PERSONAS) :
                new ObjectParameter("CANTIDAD_PERSONAS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATE_RESERVA", nUMRESERVAParameter, fECHAParameter, hORAParameter, cLIENTE_RUTParameter, cANTIDAD_PERSONASParameter);
        }
    }
}
