//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BEBIDA_BAR> BEBIDA_BAR { get; set; }
        public DbSet<BODEGA> BODEGA { get; set; }
        public DbSet<CAJA_FACTURA> CAJA_FACTURA { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<ESTADO_ORDEN> ESTADO_ORDEN { get; set; }
        public DbSet<INGREDIENTES> INGREDIENTES { get; set; }
        public DbSet<LOCAL> LOCAL { get; set; }
        public DbSet<MESA> MESA { get; set; }
        public DbSet<ORDEN> ORDEN { get; set; }
        public DbSet<ORDEN_DETALLES> ORDEN_DETALLES { get; set; }
        public DbSet<PLATO_COCINA> PLATO_COCINA { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECETA> RECETA { get; set; }
        public DbSet<RECETA_INGREDIENTE> RECETA_INGREDIENTE { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<TIPO_EMPLEADO> TIPO_EMPLEADO { get; set; }
    }
}
