//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public string RUT_EMPLEADO { get; set; }
        public string NOMBRE_EMPLEADO { get; set; }
        public string APELLIDO_PAT { get; set; }
        public string APELLIDO_MAT { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string CONTRASEÑA { get; set; }
        public Nullable<System.DateTime> FECHA_CONTRATO { get; set; }
        public string TURNO { get; set; }
        public decimal LOCAL_NUMERO_LOCAL { get; set; }
        public decimal TIPO_EMPLEADO_ID_CARGO { get; set; }
    
        public virtual LOCAL LOCAL { get; set; }
        public virtual TIPO_EMPLEADO TIPO_EMPLEADO { get; set; }
    }
}
