//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_MESA
    {
        public ESTADO_MESA()
        {
            this.MESA = new HashSet<MESA>();
        }
    
        public decimal ID_ESTADO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<MESA> MESA { get; set; }
    }
}
