//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCAL
    {
        public LOCAL()
        {
            this.EMPLEADO = new HashSet<EMPLEADO>();
            this.MESA = new HashSet<MESA>();
        }
    
        public decimal NUMERO_LOCAL { get; set; }
        public string CALLE { get; set; }
        public string COMUNA { get; set; }
        public string CIUDAD { get; set; }
        public string PAIS { get; set; }
    
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        public virtual ICollection<MESA> MESA { get; set; }
    }
}
