//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESA
    {
        public MESA()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.ORDEN = new HashSet<ORDEN>();
        }
    
        public decimal NUM_MESA { get; set; }
        public Nullable<decimal> ESTADO_MESA { get; set; }
        public decimal LOCAL_NUMERO_LOCAL { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual LOCAL LOCAL { get; set; }
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        public virtual ESTADO_MESA ESTADO_MESA1 { get; set; }
    }
}
