//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_DETALLES
    {
        public Nullable<decimal> ID_DETALLES { get; set; }
        public decimal ORDEN_NUM_ORDEN { get; set; }
        public decimal BEBIDA_BAR_ID_BEBIDA { get; set; }
        public decimal PLATO_COCINA_ID_PLATO { get; set; }
    
        public virtual BEBIDA_BAR BEBIDA_BAR { get; set; }
        public virtual ORDEN ORDEN { get; set; }
        public virtual PLATO_COCINA PLATO_COCINA { get; set; }
    }
}
