//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATO_COCINA
    {
        public PLATO_COCINA()
        {
            this.RECETA = new HashSet<RECETA>();
            this.ORDEN_PLATO = new HashSet<ORDEN_PLATO>();
        }
    
        public decimal ID_PLATO { get; set; }
        public string NOM_PLATO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public byte[] IMAGEN { get; set; }
    
        public virtual ICollection<RECETA> RECETA { get; set; }
        public virtual ICollection<ORDEN_PLATO> ORDEN_PLATO { get; set; }
    }
}
