//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.INGREDIENTES = new HashSet<INGREDIENTES>();
        }
    
        public string RUT_EMPRESA { get; set; }
        public string NOM_EMPRESA { get; set; }
        public string CORREO { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string DIRECCION_POSTAL { get; set; }
        public string SITIO_WEB { get; set; }
    
        public virtual ICollection<INGREDIENTES> INGREDIENTES { get; set; }
    }
}
