//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public RECETA()
        {
            this.RECETA_INGREDIENTE = new HashSet<RECETA_INGREDIENTE>();
        }
    
        public decimal ID_RECETA { get; set; }
        public string NOMBRE_REC { get; set; }
        public Nullable<decimal> NUM_PASO { get; set; }
        public Nullable<decimal> DESCRIPCION { get; set; }
        public decimal BEBIDA_BAR_ID_BEBIDA { get; set; }
        public decimal PLATO_COCINA_ID_PLATO { get; set; }
        public string BODEGA_NUM_BODEGA { get; set; }
    
        public virtual BEBIDA_BAR BEBIDA_BAR { get; set; }
        public virtual BODEGA BODEGA { get; set; }
        public virtual PLATO_COCINA PLATO_COCINA { get; set; }
        public virtual ICollection<RECETA_INGREDIENTE> RECETA_INGREDIENTE { get; set; }
    }
}
