//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiEat.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA_INGREDIENTE
    {
        public decimal ID_RI { get; set; }
        public string CANTIDAD_REQ { get; set; }
        public decimal RECETA_ID_RECETA { get; set; }
        public decimal INGREDIENTES_ID_INGREDIENTE { get; set; }
    
        public virtual RECETA RECETA { get; set; }
        public virtual INGREDIENTE INGREDIENTE { get; set; }
    }
}
